### ISSUE TITLE
Stuff to do before announcement

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#32]
* [x] ~~wait until HTTP merges my fix or suggests an alternative fix (open: #10)~~ change HTTP requirement to my branch with a patch.
* [x] write docs (open: #17 #5 done: #20)
* [x] reduce Readme to minimal example and move all info to docs
* [x] bring coverage > 90% (this may not be trivial) (though open: #30) 
  * unclear how to test `ws_tracker`, maybe look at docs from HTTP should be able to simulate http stream maybe or generate upgrade request
* [x] add appveyor tests and see if work (open: #29)
* [x] add license (#31)
* [x] add tags to help package discovery (#33)

**Comment by asprionj** [comment]
I can also test on Windows 10 at work (over lunchtime etc.).
Testing (also `ws_tracker`) should be doable since HTTP.jl also provides HTTP and WebSocket client functionality.

**Comment by asprionj** [comment]
Outline to test `ws_tracker`, is working but needs to be transformed into a test:
```julia
using HTTP
using Sockets
using LiveServer: ws_tracker, WS_VIEWERS

write("ws_TESTFILE.html", "A file") # create a test file to request from
empty!(WS_VIEWERS) # make sure list of viewers is empty to start with

# start ws server
server = Sockets.listen(8765)
listener = @async HTTP.listen(Sockets.localhost, 8765, server=server, readtimeout=0) do http::HTTP.Stream
    ws_tracker(http)
end

# ws client
HTTP.WebSockets.open("ws://localhost:8765/ws_TESTFILE.html") do ws
    println("websocket opened, directly returning...")
    return 0
end

show(WS_VIEWERS["ws_TESTFILE.html"]) # should be a Vector{HTTP.WebSocket.Websocket} of length 1

# clean up
close(server)
rm("ws_TESTFILE.html")
```

**Comment by tlienart** [comment]
Hmm the above doesn't quite seem to work, the `try` statement hangs. I'll open another issue for it #38

**Comment by tlienart** [comment]
Ok so the only things left to do:

* check what's going on with AppVeyor (if no news or still not working we can just remove it)
* @asprionj to do a pass on the docs and check whether it's ok for a first shot

**Comment by asprionj** [comment]
Appveyor works now. Will do the pass on the docs once you've finished all you want to do on it. Just let me know.
